export const designConfig = {
  layout: {
    pageShell: "space-y-6",
    pageInner: "space-y-6",
    pageInnerTight: "space-y-4",
    sectionGap: "space-y-6",
    gridGap: "gap-6",
    formGrid: "grid grid-cols-1 md:grid-cols-2 gap-6",
    twoColumnForm: "grid grid-cols-1 lg:grid-cols-12 gap-6 items-start",
    mainColumn: "lg:col-span-9 space-y-6",
    sideColumn: "lg:col-span-3 space-y-6 lg:sticky lg:top-6",
  },
  type: {
    pageTitle: "text-2xl sm:text-3xl font-bold tracking-tight text-foreground",
    pageSubtitle: "text-sm text-muted-foreground mt-1 leading-relaxed",
    sectionTitle: "text-base font-semibold text-foreground",
    sectionSubtitle: "text-sm text-muted-foreground",
    cardTitle: "text-base font-semibold text-foreground",
    label: "text-sm font-medium text-foreground",
    body: "text-sm text-foreground",
    helper: "text-xs text-muted-foreground",
    error: "text-xs text-destructive font-medium",
    tableText: "text-sm text-foreground",
    tableStrong: "text-sm font-medium text-foreground",
    tableMuted: "text-xs text-muted-foreground",
    caption: "text-xs text-muted-foreground",
  },
  surface: {
    page: "bg-background",
    panel: "rounded-lg border bg-card text-card-foreground shadow-sm",
    panelPadded: "p-6",
    panelHeader: "border-b pb-4 mb-6",
    tablePanel: "w-full rounded-lg border border-border/60 bg-background shadow-sm ring-1 ring-border/20 overflow-hidden",
    toolbar: "rounded-lg border bg-card p-4 shadow-sm",
    subtle: "rounded-lg border bg-muted/30",
  },
  control: {
    input: "h-10 rounded-md border-input bg-background text-sm",
    search: "h-10 pl-10 rounded-md bg-background border-border/60 text-sm",
    select: "h-9 rounded-md border-border/60 bg-background text-sm",
    button: "rounded-md text-sm font-medium",
    actionButton: "h-9 gap-2 text-sm font-medium",
    iconButton: "h-8 w-8 rounded-md",
    tabs: "rounded-md text-sm font-medium",
    switchRow: "flex items-center justify-between gap-4 rounded-lg border bg-muted/30 p-4",
  },
  data: {
    tableWrapper: "w-full rounded-lg border border-border/60 bg-background shadow-sm ring-1 ring-border/20 overflow-hidden",
    table: "w-full caption-bottom text-sm",
    tableHead: "bg-muted/40",
    tableHeadRow: "hover:bg-muted/40 border-b border-border/60",
    tableHeadCell: "h-12 px-5 text-[11px] font-semibold tracking-wider uppercase text-muted-foreground/70 whitespace-nowrap",
    tableBody: "",
    tableRow: "border-b border-border/40 last:border-0 hover:bg-muted/20 transition-all duration-200 ease-in-out group",
    tableRowSelected: "bg-muted",
    tableCell: "px-5 py-4 text-sm leading-snug",
    pagination: "flex flex-col sm:flex-row items-center justify-between gap-3 pt-4 border-t",
    empty: "flex flex-col items-center justify-center gap-3 py-20 text-muted-foreground",
    loading: "text-center py-16 text-muted-foreground",
  },
  feedback: {
    success: "text-green-600 bg-green-50 border-green-200 dark:bg-green-950/30 dark:border-green-800",
    warning: "text-yellow-700 bg-yellow-50 border-yellow-200",
    danger: "text-destructive bg-destructive/10 border-destructive/20",
    info: "text-primary bg-primary/10 border-primary/20",
    muted: "text-muted-foreground bg-muted border-border",
  },
} as const;

export type DesignConfig = typeof designConfig;
